### ISSUE TITLE
Solución acceso SSL

### ISSUE THREAD

**Issue by ivanjimenez** [sezgox/CARPOOL#1]
Prueba a crear un certificado para la máquina local, no son válidos, pero lo son para las pruebas. Lo puedes hacer con openssl o con lo que quieras. Pero como estamos en windows pues esta forma. Ya en despliegue los trataremos para los servidores.

```powershell
$cert = New-SelfSignedCertificate -CertStoreLocation Cert:\LocalMachine\My -DnsName "localhost"
$Password = ConvertTo-SecureString -String "abcd" -Force -AsPlainText
Export-PfxCertificate -Cert $cert -FilePath "C:\ruta\cert.pfx" -Password $Password

```
Fíjate que te pongo una ruta que tendrás que poner en tu equipo. 

Después colocas este fichero dentro de tu proyecto o en la ruta que te lo hayas creado, pues los certificados no suelen ir en el proyecto sino en ubicaciones en el servidor.

Luego en el `appsettings.json` para kestrel (https) no para IIS

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",

  "Kestrel": {
    "Endpoints": {
      "Https": {
        "Url": "https://localhost:7292",
        "Certificate": {
          "Path": "cert.pfx",
          "Password": "abcd"
        }
      }
    }
  }
}

```

Al lanzar la aplicación https (kestrel) te va a salir una opción seguridad para permitir en el navegador. Esto lo soluciones importando el certificado anterior al navegador como autoridad.

Ya con esto te debe funcionar.

**Comment by sezgox** [comment]
SOLUCIONADO :)
